<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="49724" started-at="2019-09-25T10:38:25Z" finished-at="2019-09-25T10:39:15Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="49724" started-at="2019-09-25T10:38:25Z" finished-at="2019-09-25T10:39:15Z">
      <class name="mainScript.DriverScript">
        <test-method status="PASS" signature="tc01()[pri:1, instance:mainScript.DriverScript@2b4bac49]" name="tc01" duration-ms="17639" started-at="2019-09-25T11:38:25Z" finished-at="2019-09-25T11:38:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc01 -->
        <test-method status="PASS" signature="tc02()[pri:2, instance:mainScript.DriverScript@2b4bac49]" name="tc02" duration-ms="4971" started-at="2019-09-25T11:38:43Z" finished-at="2019-09-25T11:38:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc02 -->
        <test-method status="PASS" signature="tc03()[pri:3, instance:mainScript.DriverScript@2b4bac49]" name="tc03" duration-ms="26897" started-at="2019-09-25T11:38:48Z" finished-at="2019-09-25T11:39:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc03 -->
        <test-method status="FAIL" signature="tc04()[pri:4, instance:mainScript.DriverScript@2b4bac49]" name="tc04" duration-ms="188" started-at="2019-09-25T11:39:15Z" finished-at="2019-09-25T11:39:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at mainScript.DriverScript.tc04(DriverScript.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc04 -->
      </class> <!-- mainScript.DriverScript -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
